### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by iendicott** [mmillmor/geo_home#29]
Hi been using this for a few weeks now and had no issues configuring the setup.
However I now have new Home Assistant hardware.
Installed the code through HACS then restarted. Next went into Settings \ Device and Services and added the Integration for Geo Home. Entered in my smartphone app username and password (which is the one I registered my account on) and received this 

[%key:common::config_flow::error::unknown%]

Have reset my password and re-logged into the my smartphone app so I know the username \ password combination is correct, tried to install the Integration again but getting the same issue.

I've just checked and the last commit might have broken something by the looks of it bit not sure what.

**Comment by iendicott** [comment]
I've just checked and the last commit has broken something by the looks of it.

**Comment by mmillmor** [comment]
I missed a flow - sorry about that. It shoud be fixed now

**Comment by iendicott** [comment]
Removed the repo from HACS rebooted and tried again after adding the integration, still the same. Sorry
